export const slides = [
  {
    title: "Luxury 3 Beds & 2 Baths Townhome in Mississauga!",
    saleInfo: "1 Assignment Sale",
    buttonText: "View Details",
    imageUrl: "/assign-mississauga.png",
    price: "$839,000.00 CAD",
    location: "Burnhamthorpe and Dixie, Mississauga, Ontario, Canada",
    type: "Townhome",
    size: "1125 SqFt",
    occupancy: "2025",
    link: "https://propertyassign.ca/assignment-for-sale/mississauga/burnhamthorpe-and-dixie",
  },
  {
    title: "3 Storey, 3 Beds & 3 Baths Townhome in Ajax!",
    saleInfo: "2 Assignment Sale",
    buttonText: "View Details",
    imageUrl: "/assign-ajax.jpg",
    price: "$859,900.00 CAD",
    location: "Hunt Street & Stonewood Street, Ajax, Ontario, Canada",
    type: "Townhome",
    size: "1839 SqFt",
    occupancy: "2025",
    link: "https://propertyassign.ca/assignment-for-sale/ajax/hunt-street-stonewood-street",
  },
  {
    title: "Premium 5 Beds & 4 Baths Detached Home in Brampton!",
    saleInfo: "3 Assignment Sale",
    buttonText: "View Details",
    imageUrl: "/assign-brampton.jpg",
    price: "$1,850,000.00 CAD",
    location: "Mayfield & Mississauga Road, Brampton, Ontario, Canada",
    type: "Detached",
    size: "3199 SqFt",
    occupancy: "2024",
    link: "https://propertyassign.ca/assignment-for-sale/brampton/mayfield-mississauga-road",
  },
  {
    title: "High-end 2 Beds & 3 Baths Townhome in Kitchener!",
    saleInfo: "4 Assignment Sale",
    buttonText: "View Details",
    imageUrl: "/assign-kitchner.jpg",
    price: "$550,000.00 CAD",
    location: "Ottawa St S & Elmsdale Dr, Kitchener, Ontario, Canada",
    type: "Townhome",
    size: "1062 SqFt",
    occupancy: "2024",
    link: "https://propertyassign.ca/assignment-for-sale/kitchener/ottawa-st-s-elmsdale-dr",
  },
  {
    title: "Spacious 3 Beds & 2 Baths Townhome in Markham!",
    saleInfo: "5 Assignment Sale",
    buttonText: "View Details",
    imageUrl: "/assign-markham.png",
    price: "$1,200,000.00 CAD",
    location:
      "Castlemore Avenue & York Regional Road 48, Markham, Ontario, Canada",
    type: "Townhome",
    size: "1953 SqFt",
    occupancy: "2025",
    link: "https://propertyassign.ca/assignment-for-sale/markham/castlemore-avenue-york-regional-road-48",
  },
];
